### PR TITLE
add next-i18next

### PR DESCRIPTION
**Pull request by JaeMeDev**
You can test by accessing /en/about and /ko/about.

https://github.com/isaachinman/next-i18next

### CODE REVIEW

**Comment by ixartz** [comment]
Hi @JaeMeDev, thank you for creating this PR. This feature is indeed asked by several people: https://github.com/ixartz/Next-js-Boilerplate/issues/13

My concern is about next-i18next, it relies on Next.js Internationalized Routing: https://nextjs.org/docs/advanced-features/i18n-routing
And, this feature will break the support for `next export`.

Is it correct? I have never tried it.

**Comment by harrybawsac** [comment]
Yes, you're right. It does break `next export`. It doesn't matter whether you use react-intl or next-i18next or any of the other packages, the base will always be the i18n stuff from next itself. And that will always break 😅

This has been a nextjs issue for years.

**Comment by ixartz** [comment]
@harrybawsac, thank you for taking to share your experience. What about not to rely on next.js for i18n? Just rely on classic react i18n package.

Currently both are supported export and non export. So, you can still enjoy `/api`, image optimization and other things.

**Comment by harrybawsac** [comment]
Seems a bit like a roundabout way when Next has i18n stuff already build in.

Also, I get this nasty feeling how everything within the i18next ecosystem is nudging developers towards using Locize.com.

**Comment by ixartz** [comment]
Haha, I have exactly the same feeling with Next.js and Vercel: the latest Next.js release are more targeting Vercel users.

**Pull request closed without merging**
