### PR TITLE
feat(ui): added shadcn ui library

### PR DESCRIPTION
**Pull request by ali-eljerrari**

### CODE REVIEW

**Comment by ixartz** [comment]
@ali-eljerrari thank you for your PR, but I not really sure we should suggest a UI library for this boilerplate.

**Comment by ixartz** [comment]
One drawback for shadcn UI compared to other library, it makes hard to switch to another library.

In your PR, it makes a lot of change in the boilerplate, which not the case when using other libraries.

In other library, you just need to do `npm install xxx` and `import Button from 'xxx'`

**Comment by ali-eljerrari** [comment]
yeah, shadcn on the other hand uses the CLI

**Comment by ixartz** [comment]
Shadcn UI CLI doesn't provide a way to uninstall the library if the developer want to change UI

**Pull request closed without merging**
