### PR TITLE
Dockerize App

### PR DESCRIPTION
**Pull request by gollc**

### CODE REVIEW

**Comment by ixartz** [comment]
@gollc Thank you for your PR and taking the time to implement the Docker support.
I'm really not a huge fan of Docker. For Dynamic site, I might consider it (but not really sure). But for static site, I'm definitively against.

Currently, there are tons of hosting providers doing an awesome job for static hosting like Vercel, Netlify, Cloudflare Page, surge.sh, etc. the list goes on. And you get a lot of features out of the box like preview in branches, etc.

**Comment by ixartz** [comment]
I see you using AWS for docker image. Why not directly using S3/Cloudfront/AWS Amplify hosting for static hosting, the Docker isn't really a need, right?

**Comment by gollc** [comment]
@ixartz Very valid points, and I agree that with a static website many of those services you mentioned do a great job (Github pages is another option). I've dockerized so I can run express with an ORM (like Prisma) and perform SSR using SWR.

I choose AWS ECR as the rest of my infrastructure is already on AWS. Configuring an Application Load Balancer (ALB) to route traffic between my different services is a huge benefit. This allows me to have API server under `mydomain.com/api/` and rest of the traffic gets routed to this express server. Having different hosting solutions introduces complexity. Usually this is solved by directing a subdomain for the API `api.mydomain.com` to the backend service. Stuff like SSL certs, CORs, session cookies, etc.

Does that make sense? 

I don't really care if this PR gets merged or closed. I just did the work so thought I'd throw up the PR.

**Comment by ixartz** [comment]
It does make sense. Thank you for taking the time to response.
Ok, I'll close the PR then.

But, I've still one question about your architecture. I totally understand you want to host everything in AWS but why using Docker/ECS? Why not using S3 or AWS Amplify hosting? You still get everything in AWS and both service can serve static content.

Or you also want everything in your AWS ECS, static website AND Api server?

**Pull request closed without merging**
