### PR TITLE
Feature/absolute imports

### PR DESCRIPTION
**Pull request by ingokpp**
Using Absolute imports is a great way to better organize NextJS projects.

### Problem

With relative imports, we have imports that look like this inside of our components.
`import { Button } from '../../../../../components/Button`

### Solution
Next.js build in Absolute Imports allow us to change this into
`import { Button } from '@/components/Button`

### CODE REVIEW

**Comment by ixartz** [comment]
Hi @ingokpp, thank you for making this feature. Indeed, I have try this feature "Absolute Imports" but it breaks the automatically VSCode automatically import.

VSCode can automatically detect a new component in the file and import it. So at the end, you never really write import { Button } from ...

**Comment by ingokpp** [comment]
Actually vscode works fine with absolute imports and even propose it. Even the nextjs docs mentions that :)

**Comment by ixartz** [comment]
Ok, it seems there is a better support now. I have tried it a the release of the new feature. It doesn't work as expected.

Could we replace:
```
"paths": {
      "@/layout/*": ["src/layout/*"],
      "@/styles/*": ["src/styles/*"],
      "@/utils/*": ["src/utils/*"],
      "@/templates/*": ["src/templates/*"],
      "@/assets/*": ["public/*"]
    }
```

by 

```
"paths": {
      "@/src/*": ["src/*"],
    }
```

src/layout, src/styles, etc... is redundant?

The last line "@/assets/*": ["public/*"] hasn't been used?

**Review by ih16 — APPROVED** [review]

**Comment by ixartz** [comment]
@ingokpp Have you a chance to address my last comment?

**Comment by ingokpp** [comment]
Hi @ixartz ,
sorry for answering late. I changed the configuration of the tsconfig file :) Now it looks much better.

**Comment by ixartz** [comment]
Hi @ingokpp, Thank you for making the changes.
Now, it looks more cleaner.

Just one question, `"@/public/*": ["./public/*"]`, what is the use for?
I didn't find where @/public has been used.
I think we should remove this line?

Otherwise, it looks good to me.

**Comment by ingokpp** [comment]
> 

The public folder is used for static file like images and favicons. If you want to include an image in your app you will mostly use the image component of nextjs and import the image from the public folder. Because this is a boilerplate i thought it would be a good idea to also include the public folder in the config for absolute imports :)

**Comment by ixartz** [comment]
Cool, learn something about image component. https://nextjs.org/docs/basic-features/image-optimization#local-images

Definitively, a great idea! I just didn't know the image component was using import from public folder. I thought it was using src with a string path.

I'm still not using Image component because hasn't support in Export mode... Already waiting for several months... Hope they release it soon.

**Pull request merged**
